# -*- coding: utf-8 -*-
"""preProcessing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cWIGy14r_nthfeM41OmgtPzt_Ebk7phI

# Dataset Location
http://shiftleft.com/mirrors/www.hpl.hp.com/india/research/penhw-resources/hpl-tamil-iso-char-offline-1.0.tar.gz
"""

!wget http://shiftleft.com/mirrors/www.hpl.hp.com/india/research/penhw-resources/hpl-tamil-iso-char-offline-1.0.tar.gz
!tar -xvf ./hpl-tamil-iso-char-offline-1.0.tar.gz

import os
import pickle
import cv2
import numpy as np
from PIL import Image
import matplotlib.pyplot as plt
import shutil

def plotIm(img_):
  plt.imshow(img_, cmap='gray')
  plt.show()
def bbox2(img1):
  img = 1 - img1
  rows = np.any(img, axis=1)
  cols = np.any(img, axis=0)
  rmin, rmax = np.where(rows)[0][[0, -1]]
  cmin, cmax = np.where(cols)[0][[0, -1]]
  return rmin, rmax, cmin, cmax
def RR(img):
    rmin, rmax, cmin, cmax = bbox2(img)
    # print(rmin, rmax, cmin, cmax)
    npArr = img[rmin:rmax, cmin:cmax]
    npArr = cv2.resize(npArr, dsize=(100, 100))
    jinga = np.ones((128,128))
    jinga[14:114,14:114] = npArr
    npArr = jinga.reshape(128, 128 , 1)
    return npArr

images=[]
labels=[]
numCategory = 12
datasetsLoc = './tamil_dataset_offline/'
w,h = 128,128
i = 0
shapeL=[]

for folders in  os.listdir(datasetsLoc):
    for files in  os.listdir(datasetsLoc+str(folders)):   
        if str(files) == 'Thumbs.db' or str(files) == 't03.tiff':
          continue      
        # print(str(folders))
        indx = int(str(files)[:3])
        if indx < numCategory:        
            image = Image.open(datasetsLoc+str(folders)+'/'+str(files))
            img=np.asarray(image, dtype=np.uint8)
            shapeL.append(img.shape)
            img2 = RR(img)
            img2 = np.asarray(img2, dtype=np.uint8)
            images.append(img2)
            labels.append(indx)
        if i%8000 == 0:
            print(str(i)+ '  ' + str(len(labels)))
        i = i + 1
filIm = open('./image_uyir_128x128.obj', 'wb')
pickle.dump(images, filIm)
filLab = open('./label_uyir_128x128.obj', 'wb')
pickle.dump(labels, filLab)

!cp /content/image_uyir_128x128.obj /content/drive/My\ Drive/wkDir/image_uyir_128x128.obj
!cp /content/label_uyir_128x128.obj /content/drive/My\ Drive/wkDir/label_uyir_128x128.obj

images=[]
labels=[]
numCategory = 156
datasetsLoc = './tamil_dataset_offline/'
w,h = 128,128
i = 0
shapeL=[]

for folders in os.listdir(datasetsLoc):
    for files in  os.listdir(datasetsLoc+str(folders)):   
        if str(files) == 'Thumbs.db' or str(files) == 't03.tiff' or str(files) == '036t01.png':
          continue      
        # print(str(folders))
        indx = int(str(files)[:3])
        if indx < numCategory:        
            image = Image.open(datasetsLoc+str(folders)+'/'+str(files))
            img=np.asarray(image, dtype=np.uint8)
            shapeL.append(img.shape)
            img2 = RR(img)
            img2 = np.asarray(img2, dtype=np.uint8)
            images.append(img2)
            labels.append(indx)
        if i%8000 == 0:
            print(str(i)+ '  ' + str(len(labels)))
        i = i + 1
filIm = open('./image_ALL_128x128.obj', 'wb')
pickle.dump(images, filIm)
filLab = open('./label_ALL_128x128.obj', 'wb')
pickle.dump(labels, filLab)

!cp /content/image_ALL_128x128.obj /content/drive/My\ Drive/wkDir/image_ALL_128x128.obj
!cp /content/label_ALL_128x128.obj /content/drive/My\ Drive/wkDir/label_ALL_128x128.obj